export class NotificationType {
    public static SHOPPING_LIST_UPDATED = "SHOPPING_LIST_UPDATED"
    public static NOTIFICATION = "NOTIFICATION"
    public static PRODUCT_UPDATED = "PRODUCT_UPDATED"
    public static USER_UPDATED = "USER_UPDATED"
    public static SHOPPING_LIST_DELETED = "SHOPPING_LIST_DELETED"
    public static PRODUCT_DELETED = "PRODUCT_DELETED"
    public static SHOPPING_LIST_SHARE_ALLOWED = "SHOPPING_LIST_SHARE_ALLOWED"
    public static SHOPPING_LIST_SHARE_CANCEL = "SHOPPING_LIST_SHARE_CANCEL"
}